[workspace]
members = ["egui_keyboard", "demo_android/rust", "demo", "demo_native"]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
eframe = { version = "0.30", features = ["wgpu", "android-game-activity"] }
egui = "0.30.0"
