[package]
name = "egui_keyboard"
version = "0.1.0"
edition = "2021"

[dependencies]
android_clipboard = "0.1.0"
egui.workspace = true

[target.'cfg(not(target_os = "android"))'.dependencies]
arboard = { version = "3.4.1", default-features = false }
